---
output:
  pdf_document: default
  html_document: default
---

# Code Book

This codebook summarizes the resulting data fields in `tidy.txt`It describes the variables and the data as asked.

## Identifiers

-   `subject` - The ID of the test subject
-   `activity` - The type of activity performed when the corresponding measurements were taken

## Measurements

-   `tBodyAccMeanX`
-   `tBodyAccMeanY`
-   `tBodyAccMeanZ`
-   `tBodyAccStdX`
-   `tBodyAccStdY`
-   `tBodyAccStdZ`
-   `tGravityAccMeanX`
-   `tGravityAccMeanY`
-   `tGravityAccMeanZ`
-   `tGravityAccStdX`
-   `tGravityAccStdY`
-   `tGravityAccStdZ`
-   `tBodyAccJerkMeanX`
-   `tBodyAccJerkMeanY`
-   `tBodyAccJerkMeanZ`
-   `tBodyAccJerkStdX`
-   `tBodyAccJerkStdY`
-   `tBodyAccJerkStdZ`
-   `tBodyGyroMeanX`
-   `tBodyGyroMeanY`
-   `tBodyGyroMeanZ`
-   `tBodyGyroStdX`
-   `tBodyGyroStdY`
-   `tBodyGyroStdZ`
-   `tBodyGyroJerkMeanX`
-   `tBodyGyroJerkMeanY`
-   `tBodyGyroJerkMeanZ`
-   `tBodyGyroJerkStdX`
-   `tBodyGyroJerkStdY`
-   `tBodyGyroJerkStdZ`
-   `tBodyAccMagMean`
-   `tBodyAccMagStd`
-   `tGravityAccMagMean`
-   `tGravityAccMagStd`
-   `tBodyAccJerkMagMean`
-   `tBodyAccJerkMagStd`
-   `tBodyGyroMagMean`
-   `tBodyGyroMagStd`
-   `tBodyGyroJerkMagMean`
-   `tBodyGyroJerkMagStd`
-   `fBodyAccMeanX`
-   `fBodyAccMeanY`
-   `fBodyAccMeanZ`
-   `fBodyAccStdX`
-   `fBodyAccStdY`
-   `fBodyAccStdZ`
-   `fBodyAccMeanFreqX`
-   `fBodyAccMeanFreqY`
-   `fBodyAccMeanFreqZ`
-   `fBodyAccJerkMeanX`
-   `fBodyAccJerkMeanY`
-   `fBodyAccJerkMeanZ`
-   `fBodyAccJerkStdX`
-   `fBodyAccJerkStdY`
-   `fBodyAccJerkStdZ`
-   `fBodyAccJerkMeanFreqX`
-   `fBodyAccJerkMeanFreqY`
-   `fBodyAccJerkMeanFreqZ`
-   `fBodyGyroMeanX`
-   `fBodyGyroMeanY`
-   `fBodyGyroMeanZ`
-   `fBodyGyroStdX`
-   `fBodyGyroStdY`
-   `fBodyGyroStdZ`
-   `fBodyGyroMeanFreqX`
-   `fBodyGyroMeanFreqY`
-   `fBodyGyroMeanFreqZ`
-   `fBodyAccMagMean`
-   `fBodyAccMagStd`
-   `fBodyAccMagMeanFreq`
-   `fBodyBodyAccJerkMagMean`
-   `fBodyBodyAccJerkMagStd`
-   `fBodyBodyAccJerkMagMeanFreq`
-   `fBodyBodyGyroMagMean`
-   `fBodyBodyGyroMagStd`
-   `fBodyBodyGyroMagMeanFreq`
-   `fBodyBodyGyroJerkMagMean`
-   `fBodyBodyGyroJerkMagStd`
-   `fBodyBodyGyroJerkMagMeanFreq`

## Activity Labels

-   `WALKING` (value `1`): subject was walking during the test
-   `WALKING_UPSTAIRS` (value `2`): subject was walking stairs up during the test
-   `WALKING_DOWNSTAIRS` (value `3`): subject was walking stairs down during the test
-   `SITTING` (value `4`): subject was sitting during the test
-   `STANDING` (value `5`): subject was standing during the test
-   `LAYING` (value `6`): subject was laying down during the test
